### ISSUE TITLE
The performance of SAC-N when N is 2

### ISSUE THREAD

**Issue by sglucas** [Howuhh/sac-n-jax#1]
Hi,

Thank you very much for your contribution. I learnt a lot from this repo.

I have a question about the performance of SAC on offline setting.

I find the performance of vanilla SAC that some papers report is very low (< 0). But I found SAC-N can achieve a great performance when N is 2 (20+) and 3 (65+) on halfcheetah-medium-v2.

So I would like to ask whether you use some tricks.

Thank you very much!

**Comment by sglucas** [comment]
Hi I think maybe that is because the environment is halfcheetah. If I use hopper, SAC-2 or SAC-3 cannot work well.

**Comment by Howuhh** [comment]
Hey @sglucas! Thank you! I'm glad you found this implementation useful. 

Actually, recently (in the end of the summer) I found the same thing! I was very excited at first, but then I was as disappointed as you are because it didn't work on more complex environments. But I found another very interesting phenomenon and wrote a short paper about it (accepted to the NeurIPS workshop), if you're interested, it's here: https://arxiv.org/abs/2211.11092 (code was written on pytorch tho, so exact training time values are a lot higher, but result still holds for jax from my experience)

**Comment by sglucas** [comment]
Hi @Howuhh Thanks for your reply!

I read your paper before and large-batch can work well is very amazing! I find LB-SAC can be much faster.

By the way, do you think td3 or td3-bc can also work well when we use a large number of critics?

Best

**Comment by Howuhh** [comment]
@sglucas Yeah, I think it's possible, but it will be worse than with SAC (from my experience and relevant work, SAC works better both online and offline).

In general, though, adding an ensemble despite the large overhead is always a good idea, it seems to me. At least give it a chance, because ensembles are good for uncertainty estimation (relevant to exploration, conservatism, model based) and for sample efficient learning (REDQ, DroQ, BootstrappedDQN, and many new approaches coming out [1](https://openreview.net/forum?id=_QzJJGH_KE), [2](https://openreview.net/forum?id=55Eet8WGJTv))

P.S. btw, if you want to look at more single-file jax implementations for online RL checkout [cleanrl](https://github.com/vwxyzjn/cleanrl) library.

**Comment by sglucas** [comment]
Hi @Howuhh Thanks for your replay again! cleanrl is also very great. To be honest, I really enjoy single-file implementations.

I find I cannot reproduce the results (about 100) of SAC-N in hopper-medium-v2 and I use  500 critics. Do you think I need to tune the hyper-parameters?

Best

**Comment by Howuhh** [comment]
Hi @sglucas! For me, this dataset was also the most difficult to reproduce. You should also keep in mind that the jax is different from the torch (in which the original was written), so there may be additional differences. 

The first thing I would try is to fix the kernel (but not the bias, it is already how it should be) initialization from he_uniform to the [default](https://pytorch.org/docs/stable/generated/torch.nn.Linear.html) in torch (maybe I will fix it myself later). Other than that, the best thing that worked for me was reducing the tau, to 1e-3 or even 5e-4. 

I'd be glad to hear if it works out for you!
